---
- name: Set Minimum password age to 0 or more days | cis minimum-password-age 1.1.3
  win_command: net accounts /minpwage:0
  register: minPassAge
  args:
    creates: C:\minPassAge.lock

- name: Create maxPassAge.lock if password history is enforced
  win_copy:
    dest: C:\minPassAge.lock
    content: ""
    force: no
  when: minPassAge

- name: Set Minimum password length to 8 or more characters | cis minimum-password-length 1.1.4
  win_command: net accounts /minpwlen:8
  register: minPassLength
  args:
    creates: C:\minPassLength.lock


- name: Create maxPassAge.lock if password history is enforced
  win_copy:
    dest: C:\minPassLength.lock
    content: ""
    force: no
  when: minPassLength



